### PR TITLE
Initial migration + Testing + CI

### PR DESCRIPTION
**Pull request by AntoineDao**
And that's my Hacktoberfest t-shirt sorted! All tests are passing and I've configured Travis to pip install `uwg` from it's git repo + run tests. There are still no geometry based tests and I have left a couple of `#Todo` comments here and there in the tests but I reckon this is a decent start.

### CODE REVIEW

**Comment by AntoineDao** [comment]
PS: Be sure to turn on Travis-CI for this repository to make sure it runs properly in the future. You can check my fork to ensure the tests are running fine on current config though.

**Comment by mostaphaRoudsari** [comment]
Should be good to go now! Can you send another PR?
https://travis-ci.org/ladybug-tools/dragonfly

**Comment by AntoineDao** [comment]
I've havent' got anything else to add at this stage. If it's ok with you do you mind merging it after taking a look at the travis report on [my fork](https://github.com/AntoineDao/dragonfly/runs/24196503)?

**Comment by AntoineDao** [comment]
Right I've made a lot of fixes to fix not so much... dragonfly installs correctly but does not install uwg with it (as it's an install from github I'm not sure how to go about it...). If it's ok let's merge it for now and fix this dependency packaging later.

**Comment by AntoineDao** [comment]
Judging by the amount of commits here it might be worth merging by squash commit to avoid my endless iterations on python packaging... :see_no_evil:

**Comment by AntoineDao** [comment]
:tada:

**Pull request merged**
